# Generated by Django 4.2.20 on 2026-01-08 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConventionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_temporaire', models.BooleanField(default=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='conventions/')),
                ('numero_convention', models.CharField(blank=True, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_passeport', models.ImageField(blank=True, null=True, upload_to='candidatures/photos_passeport/')),
                ('etudiant_prenom', models.CharField(max_length=255)),
                ('etudiant_nom', models.CharField(max_length=255)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin'), ('Autre', 'Autre')], default='Autre', max_length=20)),
                ('etudiant_email', models.EmailField(max_length=254)),
                ('etudiant_telephone', models.CharField(max_length=20)),
                ('etudiant_adresse', models.CharField(blank=True, max_length=100, null=True)),
                ('etudiant_specialite', models.CharField(max_length=100)),
                ('resume_cv', models.TextField(blank=True, null=True)),
                ('est_archivee', models.BooleanField(default=False)),
                ('date_desarchivage', models.DateTimeField(blank=True, null=True)),
                ('etudiant_niveau', models.CharField(choices=[('Licence 1', 'Licence 1'), ('Licence 2', 'Licence 2'), ('Licence 3', 'Licence 3'), ('Master 1', 'Master 1'), ('Master 2', 'Master 2')], default='Licence 3', max_length=100)),
                ('pays_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('type_stage', models.CharField(choices=[('Académique', 'Académique'), ('Fonctionnel', 'Fonctionnel'), ('Libre', 'Libre')], default='Académique', max_length=50)),
                ('statut_stage', models.CharField(default='En attente', max_length=50)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('traiter_candidature', models.BooleanField(default=False)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures/cv/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='candidatures/lettres/')),
                ('raison_refus', models.TextField(blank=True, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=20, unique=True)),
                ('score_ia', models.IntegerField(default=0, help_text='Score IA de 0 à 100')),
                ('score_details', models.JSONField(blank=True, help_text='Détails du scoring (breakdown par critère)', null=True)),
                ('score_date', models.DateTimeField(blank=True, help_text='Date du dernier calcul de score', null=True)),
                ('score_commentaire', models.TextField(blank=True, help_text='Commentaire IA sur le profil')),
                ('donnees_pre_acceptation', models.JSONField(blank=True, help_text='Données de pré-acceptation en attente de finalisation', null=True)),
                ('date_pre_acceptation', models.DateTimeField(blank=True, null=True)),
                ('convention_temporaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_associee', to='stages.conventionstage')),
            ],
            options={
                'ordering': ['-score_ia', '-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='DocumentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50)),
                ('nom_fichier', models.CharField(max_length=255)),
                ('nom_affichage', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_modifie', models.BooleanField(default=False)),
                ('hash_fichier', models.CharField(blank=True, max_length=64)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_histories', to='stages.demande')),
            ],
            options={
                'ordering': ['-date_upload'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Stagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_passeport', models.ImageField(blank=True, null=True, upload_to='stagiaires/photos_passeport/')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('niveau_etude', models.CharField(max_length=100)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin'), ('Autre', 'Autre')], default='Autre', max_length=20)),
                ('pays_residence', models.CharField(blank=True, max_length=100, null=True)),
                ('adresse', models.CharField(blank=True, max_length=255, null=True)),
                ('type_stage', models.CharField(max_length=100)),
                ('remunere', models.BooleanField(default=False, verbose_name='Stage rémunéré')),
                ('montant_remuneration', models.IntegerField(blank=True, null=True, verbose_name='Montant de la rémunération (en FCFA)')),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('date_accord', models.DateField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('resume_cv', models.TextField(blank=True, null=True)),
                ('date_debut_fige', models.DateField(blank=True, null=True, verbose_name='Date de début (figée)')),
                ('date_fin_fige', models.DateField(blank=True, null=True, verbose_name='Date de fin (figée)')),
                ('duree_jours_fige', models.IntegerField(blank=True, null=True, verbose_name='Durée en jours (figée)')),
                ('duree_mois_fige', models.IntegerField(blank=True, null=True, verbose_name='Durée en mois (figée)')),
                ('statut', models.CharField(blank=True, choices=[('À venir', 'À venir'), ('Actuel', 'Actuel'), ('Terminé', 'Terminé')], default='À venir', max_length=50, null=True)),
                ('identifiant_groupe', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('cv', models.FileField(blank=True, null=True, upload_to='candidatures/cv/')),
                ('lettre_motivation', models.FileField(blank=True, null=True, upload_to='candidatures/lettres/')),
                ('diplome', models.FileField(blank=True, null=True, upload_to='candidatures/attestations/')),
                ('pre_renouvellement_en_cours', models.BooleanField(default=False, help_text='Indique si un pré-renouvellement est en cours pour ce stage')),
                ('a_ete_renouvele', models.BooleanField(default=False, help_text='Indique si ce stage a été renouvelé (après finalisation)')),
                ('stage_renouvele_id', models.CharField(blank=True, help_text='ID du nouveau stage créé lors du renouvellement', max_length=50, null=True)),
                ('superviseur', models.CharField(blank=True, max_length=100, null=True)),
                ('donnees_pre_renouvellement', models.JSONField(blank=True, help_text='Données du pré-renouvellement en cours (dates, direction, service, etc.)', null=True)),
                ('date_pre_renouvellement', models.DateTimeField(blank=True, help_text='Date de début du pré-renouvellement', null=True)),
                ('est_renouvellement', models.BooleanField(default=False, help_text="Indique si ce stage est un renouvellement d'un stage précédent")),
                ('convention_renouvellement_temporaire', models.ForeignKey(blank=True, help_text='Convention temporaire générée lors du pré-renouvellement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaire_renouvellement_temporaire', to='stages.conventionstage')),
                ('demande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.demande')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires', to='stages.etablissement')),
                ('stage_precedent', models.ForeignKey(blank=True, help_text='Lien vers le stage précédent qui a été renouvelé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvellements', to='stages.stagiaire')),
            ],
            options={
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='StageEffectue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=100, null=True)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('niveau_etude', models.CharField(blank=True, max_length=100, null=True)),
                ('specialite', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=20, null=True)),
                ('type_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('remunere', models.BooleanField(blank=True, null=True)),
                ('montant_remuneration', models.IntegerField(blank=True, null=True)),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('lieu_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('date_debut', models.DateField(blank=True, null=True)),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('duree_jours', models.IntegerField(blank=True, null=True)),
                ('duree_mois', models.IntegerField(blank=True, null=True)),
                ('identifiant_groupe', models.UUIDField(blank=True, db_index=True, default=uuid.uuid4, null=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anciens_stages', to='stages.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('url', models.URLField(blank=True, null=True)),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('son', models.CharField(blank=True, choices=[('default', 'Son par défaut'), ('success', 'Succès'), ('warning', 'Alerte'), ('error', 'Erreur'), ('message', 'Message'), ('bell', 'Cloche'), ('chime', 'Carillon'), ('none', 'Aucun son')], default='default', max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='HistoriqueDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='stages.demande')),
            ],
        ),
        migrations.CreateModel(
            name='Entretien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(default='Entretien de stage', max_length=255)),
                ('date', models.DateField()),
                ('heure_debut', models.TimeField()),
                ('status', models.CharField(choices=[('planifié', 'Planifié'), ('annulé', 'Annulé'), ('terminé', 'Terminé')], default='planifié', max_length=20)),
                ('motif_annulation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='stages.demande')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentViewHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vue', models.DateTimeField(auto_now_add=True)),
                ('document_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.documenthistory')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_vue'],
            },
        ),
        migrations.CreateModel(
            name='Diplome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='candidatures/diplomes/')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='stages.demande')),
            ],
        ),
        migrations.CreateModel(
            name='DemandeAttestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rapport_stage', models.FileField(help_text='Rapport de stage signé', upload_to='demandes_attestation/rapports/')),
                ('demande_manuscrite', models.FileField(help_text='Demande manuscrite scannée', upload_to='demandes_attestation/demandes_manuscrites/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée')], default='en_attente', max_length=20)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('stagiaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demande_attestation', to='stages.stagiaire')),
            ],
        ),
        migrations.AddField(
            model_name='demande',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='stages.etablissement'),
        ),
        migrations.AddField(
            model_name='conventionstage',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_temporaires', to='stages.demande'),
        ),
        migrations.AddField(
            model_name='conventionstage',
            name='stagiaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire'),
        ),
        migrations.CreateModel(
            name='AttestationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='attestations_stages/')),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('stagiaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='stages.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='ActiviteStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='stages.stagiaire')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationChamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champ', models.CharField(max_length=50)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications_champs', to='stages.demande')),
            ],
            options={
                'unique_together': {('demande', 'champ')},
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=255, unique=True)),
                ('django_session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='stages_user_user_id_5f2ddf_idx'), models.Index(fields=['last_activity'], name='stages_user_last_ac_f32890_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['statut'], name='stages_stag_statut_a8c22c_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['pre_renouvellement_en_cours'], name='stages_stag_pre_ren_63c24b_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['identifiant_groupe'], name='stages_stag_identif_bb4a14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentviewhistory',
            unique_together={('utilisateur', 'document_history')},
        ),
        migrations.AddIndex(
            model_name='documenthistory',
            index=models.Index(fields=['demande', 'document_type'], name='stages_docu_demande_dd5a84_idx'),
        ),
    ]
