# Generated by Django 4.2.20 on 2026-02-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeattestation',
            name='attestation_signee',
            field=models.FileField(blank=True, help_text='Attestation de stage générée automatiquement', null=True, upload_to='demandes_attestation/attestations/'),
        ),
    ]
