# Generated by Django 4.2.20 on 2025-12-30 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraction',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='useraction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.demande'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires', to='stages.etablissement'),
        ),
        migrations.AddField(
            model_name='stageeffectue',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anciens_stages', to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='rapportstage',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rapports', to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiquedemande',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='stages.demande'),
        ),
        migrations.AddField(
            model_name='entretien',
            name='demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entretiens', to='stages.demande'),
        ),
        migrations.AddField(
            model_name='documentviewhistory',
            name='document_history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stages.documenthistory'),
        ),
        migrations.AddField(
            model_name='documentviewhistory',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documenthistory',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_histories', to='stages.demande'),
        ),
        migrations.AddField(
            model_name='diplome',
            name='demande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomes', to='stages.demande'),
        ),
        migrations.AddField(
            model_name='demandeattestation',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_attestation', to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='demandeattestation',
            name='traite_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='demande',
            name='convention_temporaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_temporaire', to='stages.conventionstage'),
        ),
        migrations.AddField(
            model_name='demande',
            name='etablissement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes', to='stages.etablissement'),
        ),
        migrations.AddField(
            model_name='conventionstage',
            name='stagiaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='attestationstage',
            name='stagiaire',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='activitestagiaire',
            name='stagiaire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activites', to='stages.stagiaire'),
        ),
        migrations.AlterUniqueTogether(
            name='verificationchamp',
            unique_together={('demande', 'champ')},
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', 'is_active'], name='stages_user_user_id_5f2ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['last_activity'], name='stages_user_last_ac_f32890_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentviewhistory',
            unique_together={('utilisateur', 'document_history')},
        ),
        migrations.AddIndex(
            model_name='documenthistory',
            index=models.Index(fields=['demande', 'document_type'], name='stages_docu_demande_dd5a84_idx'),
        ),
    ]
