# Generated by Django 4.2.20 on 2025-12-30 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionstage',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_temporaires', to='stages.demande'),
        ),
        migrations.AlterField(
            model_name='conventionstage',
            name='stagiaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stages.stagiaire'),
        ),
        migrations.AlterField(
            model_name='demande',
            name='convention_temporaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demande_associee', to='stages.conventionstage'),
        ),
    ]
