# Generated by Django 4.2.20 on 2026-02-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0002_demandeattestation_attestation_signee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandeattestation',
            name='attestation_signee',
        ),
    ]
