# Generated by Django 4.2.20 on 2025-12-30 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_conventionstage_demande_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='convention_renouvellement_temporaire',
            field=models.ForeignKey(blank=True, help_text='Convention temporaire générée lors du pré-renouvellement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaire_renouvellement_temporaire', to='stages.conventionstage'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='date_pre_renouvellement',
            field=models.DateTimeField(blank=True, help_text='Date de la pré-acceptation pour renouvellement', null=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='donnees_pre_renouvellement',
            field=models.JSONField(blank=True, help_text='Données du pré-renouvellement (type stage, dates, direction, etc.)', null=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='est_renouvellement',
            field=models.BooleanField(default=False, help_text="Indique si ce stage est un renouvellement d'un stage précédent"),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='stage_precedent',
            field=models.ForeignKey(blank=True, help_text='Lien vers le stage précédent qui a été renouvelé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvellements', to='stages.stagiaire'),
        ),
    ]
