# Generated by Django 4.2.20 on 2026-02-02 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_demandeattestation_attestation_generee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conventionstage',
            name='stagiaire_renouvellement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conventions_renouvellement_temporaires', to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='stagiaire_precedent_id',
            field=models.IntegerField(blank=True, help_text='ID du stagiaire précédent (chaîne de renouvellements)', null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='convention_renouvellement_temporaire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaire_renouvellement_temp', to='stages.conventionstage'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='date_pre_renouvellement',
            field=models.DateTimeField(blank=True, help_text='Date de pré-renouvellement', null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='donnees_pre_renouvellement',
            field=models.JSONField(blank=True, help_text='Données du pré-renouvellement en attente', null=True),
        ),
    ]
