# Generated by Django 4.2.20 on 2026-01-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0004_stagiaire_convention_renouvellement_temporaire_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stagiaire',
            options={'ordering': ['-date_debut']},
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='pre_renouvellement_en_cours',
            field=models.BooleanField(default=False, help_text='Indique si un pré-renouvellement est en cours pour ce stage'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='a_ete_renouvele',
            field=models.BooleanField(default=False, help_text='Indique si ce stage a été renouvelé (après finalisation)'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='date_pre_renouvellement',
            field=models.DateTimeField(blank=True, help_text='Date de début du pré-renouvellement', null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='donnees_pre_renouvellement',
            field=models.JSONField(blank=True, help_text='Données du pré-renouvellement en cours (dates, direction, service, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='statut',
            field=models.CharField(blank=True, choices=[('À venir', 'À venir'), ('Actuel', 'Actuel'), ('Terminé', 'Terminé')], default='À venir', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['statut'], name='stages_stag_statut_a8c22c_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['pre_renouvellement_en_cours'], name='stages_stag_pre_ren_63c24b_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['identifiant_groupe'], name='stages_stag_identif_bb4a14_idx'),
        ),
    ]
