# Generated by Django 4.2.20 on 2026-01-05 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_alter_stagiaire_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='duree_jours_fige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée en jours (figée)'),
        ),
        migrations.AddField(
            model_name='demande',
            name='duree_mois_fige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée en mois (figée)'),
        ),
        migrations.AddField(
            model_name='demande',
            name='jours_restants_fige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jours restants (figée)'),
        ),
    ]
