# Generated by Django 4.2.20 on 2026-02-02 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0005_conventionstage_stagiaire_renouvellement_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conventionstage',
            name='stagiaire_renouvellement',
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='stagiaire_precedent_id',
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='convention_renouvellement_temporaire',
            field=models.ForeignKey(blank=True, help_text='Convention temporaire générée lors du pré-renouvellement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaire_renouvellement_temporaire', to='stages.conventionstage'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='date_pre_renouvellement',
            field=models.DateTimeField(blank=True, help_text='Date de début du pré-renouvellement', null=True),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='donnees_pre_renouvellement',
            field=models.JSONField(blank=True, help_text='Données du pré-renouvellement en cours (dates, direction, service, etc.)', null=True),
        ),
    ]
