# Generated by Django 4.2.20 on 2026-01-05 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_demande_duree_jours_fige_demande_duree_mois_fige_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande',
            name='duree_jours_fige',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='duree_mois_fige',
        ),
        migrations.RemoveField(
            model_name='demande',
            name='jours_restants_fige',
        ),
    ]
