# Generated by Django 4.2.20 on 2026-04-21 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0007_alter_conventionstage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanificationRapport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=100, unique=True)),
                ('format', models.CharField(default='pdf', max_length=10)),
                ('email_destinataire', models.EmailField(max_length=254)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
