# Generated by Django 4.2.20 on 2026-01-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0007_remove_demande_duree_jours_fige_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='date_debut_fige',
            field=models.DateField(blank=True, null=True, verbose_name='Date de début (figée)'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='date_fin_fige',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin (figée)'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='duree_jours_fige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée en jours (figée)'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='duree_mois_fige',
            field=models.IntegerField(blank=True, null=True, verbose_name='Durée en mois (figée)'),
        ),
    ]
