# Generated by Django 4.2.20 on 2026-06-08 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0008_planificationrapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stagiaire',
            name='demande',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stages.demande'),
        ),
    ]
