# Generated by Django 4.2.20 on 2026-06-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0009_change_stagiaire_demande_cascade_to_set_null'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandeattestation',
            name='rapport_stage',
            field=models.FileField(blank=True, help_text='Rapport de stage signé (obligatoire pour stages académiques et libres)', null=True, upload_to='demandes_attestation/rapports/'),
        ),
    ]
