# Generated by Django 4.2.20 on 2026-06-09 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0010_make_rapport_stage_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande',
            name='statut_stage',
            field=models.CharField(choices=[('En attente', 'En attente'), ('En cours de traitement', 'En cours de traitement'), ('Pré-acceptée', 'Pré-acceptée'), ('Acceptée', 'Acceptée'), ('Refusée', 'Refusée')], default='En attente', max_length=50),
        ),
        migrations.DeleteModel(
            name='AttestationStage',
        ),
    ]
