# Generated by Django 4.2.20 on 2026-06-10 23:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0011_alter_demande_statut_stage_delete_attestationstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_notification_ajoutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email de notification des demandes',
                'verbose_name_plural': 'Emails de notification des demandes',
                'ordering': ['email'],
            },
        ),
    ]
