# Generated by Django 4.2.20 on 2026-06-11 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stages', '0012_emailnotificationdemande'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='cloture_par',
            field=models.ForeignKey(blank=True, help_text='Utilisateur ayant clôturé le dossier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_clotures', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='date_cloture',
            field=models.DateTimeField(blank=True, help_text='Si renseignée, le dossier est clôturé (verrouillé).', null=True, verbose_name='Date de clôture du dossier'),
        ),
    ]
