# Generated by Django 4.2.20 on 2026-06-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0013_stagiaire_cloture_par_stagiaire_date_cloture'),
    ]

    operations = [
        migrations.AddField(
            model_name='stagiaire',
            name='fin_anticipee',
            field=models.BooleanField(default=False, help_text='Indique que le stage a été interrompu avant son terme (fin anticipée).'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='motif_fin_anticipee',
            field=models.TextField(blank=True, help_text='Motif renseigné lors de la fin anticipée du stage.', null=True),
        ),
    ]
