# Generated by Django 4.2.20 on 2026-01-06 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('Utilisateur', 'Utilisateur'), ('Admin', 'Admin'), ('Superutilisateur', 'Superutilisateur'), ('Stagiaire', 'Stagiaire')], default='Utilisateur', max_length=20),
        ),
    ]
