# Generated by Django 4.2.20 on 2026-06-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_alter_utilisateur_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='permissions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
