# Generated by Django 4.2.20 on 2026-02-02 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0003_remove_demandeattestation_attestation_signee'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandeattestation',
            name='attestation_generee',
            field=models.FileField(blank=True, help_text='Attestation PDF générée automatiquement', null=True, upload_to='demandes_attestation/attestations_generees/'),
        ),
        migrations.AddField(
            model_name='demandeattestation',
            name='attestation_signee',
            field=models.FileField(blank=True, help_text='Attestation scannée après signature', null=True, upload_to='demandes_attestation/attestations_signees/'),
        ),
        migrations.AddField(
            model_name='demandeattestation',
            name='date_upload_attestation_signee',
            field=models.DateTimeField(blank=True, help_text="Date à laquelle l'attestation signée a été uploadée", null=True),
        ),
    ]
