# Generated by Django 4.2.20 on 2026-03-14 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stages', '0006_remove_conventionstage_stagiaire_renouvellement_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conventionstage',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='stagiaire',
            name='stage_renouvele_id',
        ),
        migrations.AddField(
            model_name='conventionstage',
            name='est_renouvellement',
            field=models.BooleanField(default=False, help_text='Indique si cette convention concerne un renouvellement'),
        ),
        migrations.AddField(
            model_name='conventionstage',
            name='stagiaire_origine',
            field=models.ForeignKey(blank=True, help_text="Stagiaire d'origine pour les conventions temporaires de renouvellement", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conventions_renouvellement_temp', to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='date_finalisation_renouvellement',
            field=models.DateTimeField(blank=True, help_text='Date de finalisation du renouvellement (étape 2)', null=True),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='nouveau_stage',
            field=models.ForeignKey(blank=True, help_text='Le nouveau stage créé lors du renouvellement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stage_origine', to='stages.stagiaire'),
        ),
        migrations.AddField(
            model_name='stagiaire',
            name='statut_renouvellement',
            field=models.CharField(blank=True, choices=[('Pré-renouvelé', 'Pré-renouvelé'), ('Renouvellement finalisé', 'Renouvellement finalisé'), ('Renouvellement annulé', 'Renouvellement annulé')], help_text='Statut détaillé du processus de renouvellement', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='conventionstage',
            name='stagiaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conventionstage', to='stages.stagiaire'),
        ),
        migrations.AlterField(
            model_name='demandeattestation',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('refusee', 'Refusée'), ('traitee', 'Traitée')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='a_ete_renouvele',
            field=models.BooleanField(default=False, help_text='Indique si ce stage a été renouvelé (après finalisation - étape 2)'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='pre_renouvellement_en_cours',
            field=models.BooleanField(default=False, help_text='Indique si un pré-renouvellement est en cours (étape 1)'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='stage_precedent',
            field=models.ForeignKey(blank=True, help_text='Le stage précédent qui a été renouvelé pour créer celui-ci', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renouvellements_suivants', to='stages.stagiaire'),
        ),
        migrations.AlterField(
            model_name='stagiaire',
            name='statut',
            field=models.CharField(blank=True, choices=[('À venir', 'À venir'), ('Actuel', 'Actuel'), ('Terminé', 'Terminé'), ('En renouvellement', 'En renouvellement')], default='À venir', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='conventionstage',
            index=models.Index(fields=['est_temporaire'], name='stages_conv_est_tem_ab1582_idx'),
        ),
        migrations.AddIndex(
            model_name='conventionstage',
            index=models.Index(fields=['est_renouvellement'], name='stages_conv_est_ren_5f17a2_idx'),
        ),
        migrations.AddIndex(
            model_name='conventionstage',
            index=models.Index(fields=['stagiaire_origine'], name='stages_conv_stagiai_58505b_idx'),
        ),
        migrations.AddIndex(
            model_name='conventionstage',
            index=models.Index(fields=['stagiaire'], name='stages_conv_stagiai_bce1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='conventionstage',
            index=models.Index(fields=['demande'], name='stages_conv_demande_263c1e_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['statut_renouvellement'], name='stages_stag_statut__9e9fd0_idx'),
        ),
        migrations.AddIndex(
            model_name='stagiaire',
            index=models.Index(fields=['a_ete_renouvele'], name='stages_stag_a_ete_r_ec57ff_idx'),
        ),
    ]
